default_roles:
  - system
  - aldente
  - asciiquarium
  - bash
  - bat
  - browsers
  - btop
  - claude
  # - discord
  # - docker
  - fish
  - flatpak
  - fonts
  - fzf
  - gh
  - ghostty
  - git
  - gnome
  - go
  - hammerspoon
  - helm
  - jellyfin
  - jj
  # - k8s
  - k9s
  - kitty
  - lazygit
  - lsd
  - lua
  - nala
  - ncdu
  - neofetch
  - neovim
  - nerdfetch
  - npm
  - nvm
  - obsidian
  - oh-my-posh
  - podman
  - pwsh
  - python
  - raycast
  # - ruby
  # - rust
  - slides
  - spotify
  - ssh
  - sshfs
  - starship
  - taskfile
  - terraform
  - terragrunt
  - tldr
  - tmate
  - tmux
  - sesh
  # - tshark
  - warp
  - whalebrew
  # - zellij
  - zoxide
  - zsh

git_user_name: "idunkoncode"
git_user_email: "idunkoncode@proton.me"

# SSH Configuration
ssh_keys:
  - name: id_ed25519
    type: ed25519
  - name: id_rsa
    type: rsa

k8s:
  repo:
    version: "v1.26"

helm:
  repos:
    - name: traefik
      url: https://helm.traefik.io/traefik

go:
  packages:
    - package: github.com/go-task/task/v3/cmd/task@latest
      cmd: task
    - package: github.com/joshmedeski/sesh/v2@latest
      cmd: sesh
    # NOTE: termshark has dependency issues with v2.4.0
    # - package: github.com/stillmatic/chat@latest
    #   cmd: chat

# Fish shell configuration
fish_config: true
fish_set_default: true

# Oh My Posh configuration
oh_my_posh_theme: "catppuccin_mocha.omp.json"

# GNOME configuration
gnome_shell_theme: "Yaru-dark"
gnome_gtk_theme: "Yaru-dark"
gnome_icon_theme: "Papirus-Dark"
gnome_cursor_theme: "Yaru"
gnome_wallpaper: "/usr/share/backgrounds/opensuse/openSUSE-default.xml"

# Browser configuration
browsers_install_chrome: true
browsers_install_edge: true
browsers_install_firefox: true
