---
# Install rustup on Debian
- name: "Rust | {{ ansible_distribution }} | Install curl (required for rustup)"
  ansible.builtin.apt:
    name: curl
    state: present
    update_cache: true
  become: true

- name: "Rust | {{ ansible_distribution }} | Download and install rustup"
  ansible.builtin.shell: |
    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
  args:
    creates: "{{ ansible_env.HOME }}/.cargo/bin/rustup"
  environment:
    HOME: "{{ ansible_env.HOME }}"

- name: "Rust | {{ ansible_distribution }} | Initialize rustup environment"
  ansible.builtin.shell: |
    source {{ ansible_env.HOME }}/.cargo/env
    rustup default stable
  args:
    creates: "{{ ansible_env.HOME }}/.cargo/bin/cargo"
  environment:
    HOME: "{{ ansible_env.HOME }}"
