---
- name: "Flatpak | Install flatpak"
  ansible.builtin.package:
    name: flatpak
    state: present
  become: true

- name: "Flatpak | Add Flathub remote"
  community.general.flatpak_remote:
    name: "flathub"
    flatpakrepo_url: "https://flathub.org/repo/flathub.flatpakrepo"
    state: present
  become: true

- name: "Flatpak | Install Jellyfin Server"
  community.general.flatpak:
    name: org.jellyfin.JellyfinServer
    state: present
  become: true

- name: "Flatpak | Install Jellyfin MPV Shim"
  community.general.flatpak:
    name: com.github.iwalton3.jellyfin-mpv-shim
    state: present
  become: true
