---
- name: "{{ role_name }} | Checking for Distribution Config: {{ ansible_distribution }}"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_distribution }}.yml"
  register: distribution_config

- name: "{{ role_name }} | Run Tasks: {{ ansible_distribution }}"
  ansible.builtin.include_tasks: "{{ ansible_distribution }}.yml"
  when: distribution_config.stat.exists

- name: "{{ role_name }} | Ensure .config directory exists"
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.config"
    state: directory
    mode: "0755"

- name: "{{ role_name }} | Copy oh-my-posh theme"
  ansible.builtin.copy:
    src: "{{ oh_my_posh_theme | default('catppuccin_mocha.omp.json') }}"
    dest: "{{ ansible_user_dir }}/.config/{{ oh_my_posh_theme | default('catppuccin_mocha.omp.json') }}"
    mode: "0644"
  tags:
    - oh-my-posh
